/*********************************************************** {COPYRIGHT-TOP} ***
* Copyright 2016 IBM Corporation
*
* All rights reserved. This program and the accompanying materials
* are made available under the terms of the MIT License
* which accompanies this distribution, and is available at
* http://opensource.org/licenses/MIT   	
************************************************************ {COPYRIGHT-END} **/
package com.ibm.uk.hursley.perfharness;

/******************************************************************************
* NOTE: I am automatically generated by build.xml...  (don't forget to run it twice!)
* NOTE2: This class needs to be deleted once a year!
******************************************************************************/
public final class Copyright {

 public final static String COPYRIGHT =
      "Copyright 2016 IBM Corporation"
    + "\n\nAll rights reserved. This program and the accompanying materials"
    + "\nare made available under the terms of the MIT License"
    + "\nwhich accompanies this distribution, and is available at"
	+ "\nhttp://opensource.org/licenses/MIT ";
}
	    